import {
  FaCaretDown,
  FaCaretUp,
  FaTwitter,
  FaFacebookSquare,
  FaInstagram,
  FaYoutube,
} from "react-icons/fa";

export const followerCardContent = [
  {
    id: 1,
    socialIcon: <FaFacebookSquare />,
    arrowIcon: <FaCaretUp />,
    username: "@nathanf",
    followers: 1987,
    updates: 12,
    color: "var(--clr-facebook)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 2,
    socialIcon: <FaTwitter />,
    arrowIcon: <FaCaretUp />,
    username: "@nathanf",
    followers: 1044,
    updates: 90,
    color: "var(--clr-twitter)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 3,
    socialIcon: <FaInstagram />,
    arrowIcon: <FaCaretUp />,
    username: "@realnathanf",
    followers: "11k",
    updates: 1099,
    color: "var(--clr-instagram-light)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 4,
    socialIcon: <FaYoutube />,
    arrowIcon: <FaCaretDown />,
    username: "Nathan F.",
    followers: 8239,
    updates: 144,
    color: "var(--clr-youtube)",
    smallClr: "var(--clr-red)",
  },
];
export const statsCardContent = [
  {
    id: 1,
    statName: "Page Views",
    socialIcon: <FaFacebookSquare />,
    arrowIcon: <FaCaretUp />,
    count: 87,
    updates: 3,
    color: "var(--clr-facebook)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 2,
    statName: "Likes",
    socialIcon: <FaFacebookSquare />,
    arrowIcon: <FaCaretDown />,
    count: 52,
    updates: 2,
    color: "var(--clr-facebook)",
    smallClr: "var(--clr-red)",
  },
  {
    id: 3,
    statName: "Likes",
    socialIcon: <FaInstagram />,
    arrowIcon: <FaCaretUp />,
    count: 5462,
    updates: 2257,
    color: "var(--clr-instagram-dark)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 4,
    statName: "Profile Views",
    socialIcon: <FaInstagram />,
    arrowIcon: <FaCaretUp />,
    count: "52k",
    updates: 1375,
    color: "var(--clr-instagram-dark)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 5,
    statName: "Retweets",
    socialIcon: <FaTwitter />,
    arrowIcon: <FaCaretUp />,
    count: 117,
    updates: 303,
    color: "var(--clr-twitter)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 6,
    statName: "Likes",
    socialIcon: <FaTwitter />,
    arrowIcon: <FaCaretUp />,
    count: 507,
    updates: 553,
    color: "var(--clr-twitter)",
    smallClr: "var(--clr-green)",
  },
  {
    id: 7,
    statName: "Likes",
    socialIcon: <FaYoutube />,
    arrowIcon: <FaCaretDown />,
    count: 107,
    updates: 19,
    color: "var(--clr-youtube)",
    smallClr: "var(--clr-red)",
  },
  {
    id: 8,
    statName: "Total Views",
    socialIcon: <FaYoutube />,
    arrowIcon: <FaCaretDown />,
    count: 1407,
    updates: 12,
    color: "var(--clr-youtube)",
    smallClr: "var(--clr-red)",
  },
];
